# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Bump Version on release created'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type:  'patch'
          tag-prefix:  'v'
