name: Pre Check

on:
  push:
    branches: 
      - 'feature/**'

jobs:
  deploy-storybook:
    name: "Pre Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - run: npm install
      - run: npm run-script prepublish
      - run: npm run-script build-storybook